

# website settings
website:
  title: "Nihit_N._Mehta"                             
  description: "Nihit: Cooking Up Creativity, Writing From the Heart, and Staying Strong!"   
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Published Works and Education"
        href: publishedworksandeducation/index.qmd
      - text: "Interests"
        href: interests/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Scientific Insights and Blogs"
        href: Scientific Insights and Blogs/index.qmd
    
    # your social media handles
    right:
      - icon: instagram
        href: https://www.instagram.com/nnmehta08?igsh=MXFmeDZuMnY0Z25qMg%3D%3D&utm_source=qr
      - icon: linkedin
        href: https://www.linkedin.com/in/marvin-schmitt-a85b321a2/
      - icon: envelope
        aria-label: email
        href: "mailto:nnm32@case.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
   
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true